mypage/urls.py
from django.contrib import admin
from django.urls import path, include
from mypage import views
from mypage.views import add_status, add_profile, validate_form, logout
from mypage.views import index, profile, books, search_book, registration
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [    
    path(r'index/', index, name = 'index'),
    path(r'registration/', registration, name = 'registration'),
    path(r'profile/', profile, name = 'profile'),
    path(r'books/', books, name = 'books'),
    path('search_book/<text>/', search_book, name='search_book'),
    url(r'^$', index, name='index'),
    url(r'add_status/$', add_status, name='add_status'),
    url(r'logout/$', logout, name='logout'),
    url(r'add_profile/$', add_profile, name='add_profile'),
    url(r'^ajax/validate_form/$', validate_form, name='validate_form'),
]

urlpatterns += staticfiles_urlpatterns()

newsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from mypage.views import index, registration
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'index/', index, name = 'index'),
    path(r'registration/', registration, name = 'registration'),
    path('', include(('mypage.urls','mypage'),namespace='mypage')),
    url(r'^mypage/', include(('mypage.urls', 'mypage'), namespace='mypage')),
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
]

urlpatterns += staticfiles_urlpatterns()

mypage/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    text = models.TextField()
    
class Profile(models.Model):
    email = models.CharField(max_length=200)
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    confirm_password = models.CharField(max_length=200)

mypage/forms.py
from django import forms

class Status_Form(forms.Form):
	error_messages = {
        'required': 'This field is required',
        'invalid': 'is not valid',
	}

	attrs = {
        'class': 'form-control'
	}
	text = forms.CharField(label='status', required=True, max_length=300,
	widget=forms.TextInput(attrs=attrs))
    
class Profile_Form(forms.Form):
    error_messages = {
        'required': 'This field is required',
        'invalid': 'is not valid',
    }

    attrs = {
        'class': 'form-input',
        'type':'text'
    }
    
    def merge_two_dicts(x, y):
        z = x.copy()   # start with x's keys and values
        z.update(y)    # modifies z with y's keys and values & returns None
        return z
    
    adi_attrs = {
        'id': 'form-email',
        'placeholder': 'Email',
        'name': 'email'
    }
    email = forms.CharField(label='email', required=True, max_length=300,
    widget=forms.TextInput(attrs=merge_two_dicts(attrs, adi_attrs)))
    
    adi_attrs = {
        'id': 'form-username',
        'placeholder': 'Username',
        'name': 'username'
    }
    username = forms.CharField(label='username', max_length=300,
    widget=forms.TextInput(merge_two_dicts(attrs, adi_attrs)))
    
    adi_attrs = {
        'id': 'form-password',
        'placeholder': 'Password',
        'name': 'password',
        'type':'password'
    }
    password = forms.CharField(label='password', max_length=300,
    widget=forms.TextInput(attrs=merge_two_dicts(attrs, adi_attrs)))
    
    adi_attrs = {
        'id': 'form-confirm-password',
        'placeholder': 'Confirm Password',
        'name': 'confirm password',   
        'type':'password'
    }
    confirm_password = forms.CharField(label='confirm_password', max_length=300,
    widget=forms.TextInput(attrs=merge_two_dicts(attrs, adi_attrs)))

mypage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, JsonResponse
from .forms import Status_Form, Profile_Form
from .models import Status, Profile
from django.contrib.auth import logout as logout_user
from django.template import RequestContext
import json
import requests

# Create your views here.

def index(request):
	all_status = Status.objects.all()
	form = Status_Form
	return render(request, 'index.html', {'Status': all_status, 'form': form, 'nbar': 'index'})

def profile(request):
	return render(request, 'profile.html', {'nbar': 'profile'})

def logout(request):
    logout_user(request)
    return HttpResponseRedirect('/registration/')

def books(request):
    return render(request, 'books.html', {'nbar': 'books',
                                         'context_instance': RequestContext(request)})

def registration(request):
	form = Profile_Form
	return render(request, 'registration.html', {'form': form, 'nbar': 'registration'})

def validate_form(request):
    username = request.GET.get('username', None)
    email = request.GET.get('email', None)
    password = request.GET.get('password', None)
    confirm_password = request.GET.get('confirm_password', None)
    
    v_email = Profile.objects.filter(email=email).exists()
    v_password = True if (password == confirm_password) else False
    v_all = not v_email and email and username and password and confirm_password and v_password
    
    data = {
        'is_taken': v_email,
        'is_equal': v_password,
        'is_submitable': v_all
    }
    
    return JsonResponse(data)

def add_profile(request):
    print("im here")
    form = Profile_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        email = request.POST.get('email', False)
        username = request.POST.get('username', False)
        password = request.POST.get('password', False)
        confirm_password = request.POST.get('confirm_password', False)

        profile = Profile(email=email,
                          username=username,
                          password=password,
                          confirm_password=confirm_password)
        
        profile.save()
        return redirect(registration)
    else:
        return HttpResponseRedirect('/registration/')

def search_book(request, text=None):
    url = 'https://www.googleapis.com/books/v1/volumes?q='+text
    return JsonResponse(requests.get(url).json())

def add_status(request):
	form = Status_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		text = request.POST.get('text', False)
		text = Status(text=text)
		text.save()
		return redirect(index)
	else:
		return HttpResponseRedirect('/mypage:index/')
    
def favorite(request):
    book_data = json.loads(request.body.decode())
    
    added = book_data['added']
    length = request.session.get('length', 0)

    if(added == 'true'):
        request.session['length'] = length+1
    else:
        request.session['length'] = length-1
        
    return JSONResponse({'length': request.session['length']})

mypage/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static from staticfiles %}
    <head>
        
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>My Website</title>

        <!-- Custom styles for this template -->
        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        
    </head>

    <body onload="myFunction()">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="{% static 'js/script.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/X.Y.Z/angular-route.js"></script>
        
        <div id="loader" class="boxLoading"></div>
        
        <div id="myDiv" class="animate-bottom">
            <header>
                {% include "partials/header.html" %}
            </header>

            <div class="wrapper">
                {% block content %}
                {% endblock %}
            </div>

            <footer>
                {% include "partials/footer.html" %}
            </footer>
        </div>
    </body>
</html>

mypage/templates/books.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}

<section id="table_wrapper" class="py-5 head-article shadow">
    
    <div class="container">
        <div>
            {% if user.is_authenticated %}
                <p class="display-4">Hello, {{ user.username }}</p>
                <a href="{% url 'mypage:logout' %}">Logout</a>
            {% endif %}
            <h2 id="countingStar" style="vertical-align:middle;">
                <i class="material-icons" style="vertical-align:middle;font-size:50px">grade</i>Favourite Books: <span id="fav-counter">{{ request.session.length }}</span>
            </h2>
        </div>
    </div>
    
    <div class="container mb-3 overflow-hide">
        <input class="form-control" id="myinput" type="text" name="search_input">
        <button id="button-input" class="btn btn-outline-warning" onclick="getJSONData()" style="width:15%;" name="action">input
            <i class="va-middle material-icons right">done</i>
        </button>
    </div>
    
    <div class = "table-book">
        <table class="container table-info" id="book_table">
            <thead>
                <tr>
                    <th><h1>Thumbnail</h1></th>
                    <th><h1>Title</h1></th>
                    <th><h1>Published Date</h1></th>
                    <th><h1>Add to Favourite</h1></th>
                </tr>
            </thead>
            <tbody id="maBody"></tbody>
        </table>
    </div>
</section>
{% endblock %}

mypage/templates/index.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}
<!-- Content section -->
<section class="py-5 head-article shadow">
    <div id="article-container" class="container con-desc">
        <h1>Hello, Apa kabar?</h1>

        <form class="col s12 container" id="reg-form" method="post" action="/mypage:add_status/">
            {% csrf_token %}
            {{ form.text }}
            <div class="mt-3">
                <button id="button-input" class="btn btn-outline-warning float-none" type="submit" name="action">input
                    <i class="va-middle material-icons right">done</i>
                </button>
            </div>
        </form>
    </div>
</section>

<section class="spacer bg-theme"></section>
<!-- Content section -->
<section class="py-5 head-article shadow">
    <div class="container">
        <h2>Status Section</h2>
        <div class="container" style="margin-top: 20px;">
        {% for status in Status %}
            <p> {{ status.text }} </p>
        {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

mypage/templates/partials/footer.html
<!-- Footer -->
<footer id="footer" class="py-5 bg-theme">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; -My Website- Kevin Luvian Herdianto PPW2018</p>
  </div>
</footer>

mypage/templates/partials/header.html
<!-- Navigation -->
<nav id="navbar-top" class="navbar navbar-expand-lg navbar-dark bg-theme fixed-top shadow">
  <div class="container">
    <a id="header-title" class="navbar-brand" href="#">Kevin LH</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link {% if nbar == 'index' %}active{% endif %}" href="{% url 'mypage:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if nbar == 'profile' %}active{% endif %}" href="{% url 'mypage:profile' %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if nbar == 'books' %}active{% endif %}" href="{% url 'mypage:books' %}">Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if nbar == 'registration' %}active{% endif %}" href="{% url 'mypage:registration' %}">Registration</a>
        </li>
        <li class="nav-item">
            <a><button id="button-theme-changer" name="button-theme-changer" class="btn btn-light"> change theme </button></a>
        </li>
      </ul>
    </div>
  </div>
</nav>

mypage/templates/profile.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}
<!-- Header - set the background image for the header in the line below -->
<header class="py-5 bg-image-full" style="background-image: url({% static 'img/Abstract.png' %});">
  <img class="img-fluid d-block mx-auto img-profile" src="{% static 'img/profile.png' %}" alt="">
</header>

<!-- Content section -->
<section class="py-5 head-article shadow">
  <div class="container con-desc">
    <h1>Kevin Luvian Herdianto</h1>
    <p class="lead">Mahasiswa di Universitas Indonesia<br>Banten, Indonesia</p>
      <button class="btn btn-lg btn-fav btn-msg text-white bg-theme"><h3>message+</h3></button>
  </div>
</section>

<section class="spacer bg-theme"></section>
<!-- Content section -->
<section class="py-5 head-article shadow">
    <div class="accordion container">
        <ul>
            <li>
                <a class="toggle" href="javascript:void(0);"><h3 class="text-center">Contacts</h3></a>
                <ul class="inner text-center">
                    <li><p>Email: wkeplon@gmail.com<br>Phone: 081219052255</p></li>
                </ul>
            </li>

            <li>
                <a class="toggle" href="javascript:void(0);"><h3 class="text-center">Bio</h3></a>
                <ul class="inner text-center">
                    <li><p class="text-justify" style="margin-right: 30px;">Saya sekarang berumur 19 tahun sedang melaksanakan pendidikan S1 Sistem Indormasi di Universitas Indonesia, memiliki kondisi kesehatan yang sangat baik. Selain mampu berkomunikasi dengan bahasa indonesia yang baik, saya juga mahir dalam berbahasa inggris secara lisan dan tulisan. Latar belakang pendidikan saya baik tanpa mengalami kendala dan selalu mendapatkan hasil yang memuaskan. Sifat saya ramah, gigih, dan fokus sehingga dapat bekerjasama secara efisien dalam suasana tim dengan baik.</p></li>
                </ul>
            </li>
            
            <li>
                <a class="toggle" href="javascript:void(0);"><h3 class="text-center">Organization</h3></a>
                <ul class="inner text-center date-activity">
                    <li><p style="margin-top:10px;"><span>2016 - 2017</span> Rohis SMAN 90 Jakarta Selatan</p></li>
                </ul>
            </li>

            <li>
                <a class="toggle" href="javascript:void(0);"><h3 class="text-center">Skills</h3></a>
                <ul class="inner">
                    <li>
                        <a href="#" class="toggle">Photoshop</a>
                        <div class="inner">
                            <div class="skills-elm" style="margin-bottom:0;padding-left: 5%;">
                                <img class="k_pic" src="{% static 'img/Software/Photoshop.png' %}" alt="pic">
                                <div class="con-skillset">
                                    <div class="blocks">
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block gray"></div>
                                        <div class="block gray"></div>
                                        <div class="block gray"></div>
                                    </div>
                                </div>
                             </div>
                        </div>
                    </li>
                    
                    <li>
                        <a href="#" class="toggle">Blender3D</a>
                        <div class="inner">
                            <div class="skills-elm" style="margin-bottom:0;padding-left: 5%;">
                                <img class="k_pic" src="{% static 'img/Software/Blender3D.png' %}" alt="pic">
                                <div class="con-skillset">
                                    <div class="blocks">
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block gray"></div>
                                        <div class="block gray"></div>
                                        <div class="block gray"></div>
                                        <div class="block gray"></div>
                                        <div class="block gray"></div>
                                    </div>
                                </div>
                             </div>
                        </div>
                    </li>
                    
                    <li>
                        <a href="#" class="toggle">Java</a>
                        <div class="inner">
                            <div class="skills-elm" style="margin-bottom:0;padding-left: 5%;">
                                <img class="k_pic" src="{% static 'img/Software/Java.png' %}" alt="pic">
                                <div class="con-skillset">
                                    <div class="blocks">
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block gray"></div>
                                        <div class="block gray"></div>
                                        <div class="block gray"></div>
                                        <div class="block gray"></div>
                                        <div class="block gray"></div>
                                        <div class="block gray"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    
                    <li>
                        <a href="#" class="toggle">Python</a>
                        <div class="inner">
                            <div class="skills-elm" style="margin-bottom:0;padding-left: 5%;">
                                <img class="k_pic" src="{% static 'img/Software/Python.png' %}" alt="pic">
                                <div class="con-skillset">
                                    <div class="blocks">
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block bg-theme"></div>
                                        <div class="block gray"></div>
                                        <div class="block gray"></div>
                                        <div class="block gray"></div>
                                        <div class="block gray"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</section>
<script>
    var abstract_default = "url({% static 'img/Abstract.png' %})";
    var abstract_black = "url({% static 'img/AbstractBlack.png' %})";
    var abstract_blue = "url({% static 'img/AbstractBlue.png' %})";
</script>
{% endblock %}

mypage/templates/registration.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}
<section class="pt-41 bg-theme">
    <div class='login text-white'>
        <h2>Register an Account</h2>
        <form class="form" method="post" action="/mypage:add_profile/">
            {% csrf_token %}
            <fieldset class="form-fieldset">
                {{ form.username }} <span id="e-username" class="cl-danger"></span>
            </fieldset>
            <fieldset id="fl-email" class="form-fieldset">
                {{ form.email }} <span id="e-email" class="cl-danger"></span>
            </fieldset>
            <fieldset class="form-fieldset">
                {{ form.password }} <span id="e-password" class="cl-danger"></span>
            </fieldset>
            <fieldset id="fl-confirm-password" class="form-fieldset">
                {{ form.confirm_password }} <span id="e-confirm-password" class="cl-danger"></span>
            </fieldset>
            <button id="btn-form" class="btn btn-form bg-theme-dark" type="submit" name="action" disabled>Create Account</button>
        </form>
        
        <p><strong>-- OR --</strong></p>
        <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a>
    </div>
</section>

<script>
    $(".form-input").change(function () {
        var email = $('#form-email').val();
        var username = $('#form-username').val();
        var password = $('#form-password').val();
        var confirm_password = $('#form-confirm-password').val();
    
        $.ajax({
            url: '/ajax/validate_form/',
            data: {
                'username': username,
                'email': email,
                'password': password,
                'confirm_password': confirm_password
            },

            dataType: 'json',
            success: function (data) {
                if (data.is_taken) {
                    $('#e-email').text("A user with this email already exists");
                    $('#fl-email').css("padding-bottom","0");
                } else {
                    $('#e-email').text("");
                    $('#fl-email').css("padding-bottom","24px");
                }
                
                if (data.is_equal) {
                    $('#e-confirm-password').text("");
                    $('#fl-confirm-password').css("padding-bottom","24px");
                } else {
                    $('#e-confirm-password').text("Password is not the same");
                    $('#fl-confirm-password').css("padding-bottom","0");
                }
                
                if(data.is_submitable) {
                    $('#btn-form').prop('disabled', false);
                    $('#btn-form').addClass('animated');
                } else {
                    $('#btn-form').prop('disabled', true);
                    $('#btn-form').removeClass('animated');
                }
                console.log(data.is_submitable);
            }
        });
    });
</script>
{% endblock %}